name: Lacework SCA/SAST Pull Request


on: 
 
  pull_request: 
    branches: 
      - master  


jobs: 
  build: 
    runs-on: ubuntu-latest  

    steps: 
      # Step 1: Checkout full repo with history
      - name: Checkout repository
        uses: actions/checkout@v3
        #with:
        #  fetch-depth: 0
        #  token: ${{ secrets.GITHUB_TOKEN }}

      # Step 2: Install, configure and run FortiCNAPP
      - name: Install Lacework CLI
        run: |
          curl https://raw.githubusercontent.com/lacework/go-sdk/main/cli/install.sh | bash 
          lacework configure -a ${{ secrets.LW_ACCOUNT }}.lacework.net \
                             -k ${{ secrets.LW_API_KEY }} \
                             -s ${{ secrets.LW_API_SECRET }} \
                             --noninteractive 
          lacework component install sca 
          #git checkout ${{ github.event.pull_request.head.sha }}
          #lacework sca scan ./ -f sarif -o /tmp/lacework-scan-source.json 
          #lacework sca scan ./ -f sarif -o results.sarif --save-results
          lacework sca scan ./ -f sarif -o lacework-scan.sarif --save-results

      - name: Check for failure criteria
        env:
          SCA_HIGH: pass
          SCA_CRIT: pass
          SAST_HIGH: pass
          SAST_CRIT: pass
        run: |
          bash <(curl -sSL https://raw.githubusercontent.com/FortiLatam/FCNAPP-tools/refs/heads/main/Code-Security/azdo-fail-codesec.sh)


      # Step 4: Run Lacework SCA Scan on target (base) branch
      #- name: Run Lacework SCA Scan on Target Branch 
       # run: |
        #  git checkout ${{ github.event.pull_request.base.sha }}
         # lacework sca scan ./ -f sarif -o /tmp/lacework-scan-target.json 

      # Step 5: Compare results and generate SARIF
      #- name: Compare JSON Files and Generate SARIF 
      #  run: |
      #    git checkout ${{ github.event.pull_request.head.sha }}
      #    lacework sca compare --new /tmp/lacework-scan-source.json \
      #                         --old /tmp/lacework-scan-target.json \
      #                         --formats sarif \
      #                         -o results.sarif 

      # Step 6: Upload SARIF to GitHub Security tab
      - name: Upload SARIF File 
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
          category: lacework-sca
          ref: refs/pull/${{ github.event.pull_request.number }}/head
          sha: ${{ github.event.pull_request.head.sha }}


      # (Opcional) Step 7: Upload SARIF como artifact para download manual
      #- name: Upload SARIF Artifact
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: lacework-comparison-report
      #    path: results.sarif
